export const SicknessGroupList= {
  4: ["Trastornos de la glandula tiroides",
    "Diabetes mellitus",
    "Otros trastornos de la regulación de la glucosa y pancreas",
    "Trastornos de otras glandulas endocrinas",
    "Desnutricion",
    "Otras deficiencias nutricionales",
    "Obesidad y otros tipos de hiperalimentación",
    "Trastornos metabolicos"],
  5: ["Trastornos mentales organicos",
    "Trastornos debidos al uso de sustancias psicoactivas",
    "Esquizofrenia, trastornos esquizotipicos y trastornos delirantes",
    "Trastornos del  humor (afectivos)",
    "Trastornos neuróticos, relacionados con el estrés y trastornos somatomorfos",
    "Sindromes del comportamiento por alteraciones fisiologicas y factores fisicos",
    "Trastornos de la personalidad y del comportamiento en adultos",
    "Retraso mental",
    "Trastornos del desarrollo psicologico",
    "Trastornos de la niniez y adolescencia",
    "Trastorno mental no especificado"],
  6: ["Enfermedades inflamatorias del sistema nervioso central",
    "Atrofias sistemicas",
    "Trastornos extrapiramidales y del movimiento",
    "Otras enfermedades degenerativas del sistema nervioso",
    "Enfermedades desmielinizantes del sistema nervioso central",
    "Trastornos episodicos y paroxisticos",
    "Trastornos de los nervios",
    "Polineuropatias y otros trastornos del sistema nervioso periferico",
    "Enfermedades musculares y de la unión neuromuscular",
    "Paralisis cerebral y otros sindromes paraliticos",
    "Otros trastornos del sistema nervioso",],
  9: ["Fiebre reumatica aguda",
    "Enfermedades cardiacas reumaticas cronicas",
    "Enfermedades hipertensivas",
    "Enfermedades isquemicas del corazon",
    "Enfermedad cardiopulmonar",
    "Otras formas de enfermedad del corazón",
    "Enfermedades cerebrovasculares",
    "Enfermedades de las arterias",
    "Enfermedades de las venas",
    "Otros trastornos del sistema circulatorio",],
  10: ["Infecciones agudas de las vias respiratorias superiores",
    "Influenza (gripe) y neumonia",
    "Infecciones agudas de las vias respiratorias inferiores",
    "Otras enfermedades de las vias respiratorias superiores",
    "Enfermedades cronicas de las vias respiratorias inferiores",
    "Enfermedades del pulmon por agentes externos",
    "Otras enfermedades respiratorias",
    "Afecciones supurativas y necroticas de las vias respiratorias inferiores",
    "Otras enfermedades de la pleura",
    "Otras enfermedades del sistema respiratorio",]
};

export type SicknessKey = keyof typeof SicknessGroupList;
export type SicknessValue = typeof SicknessGroupList[SicknessKey];