version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: simple_dev_docker  # Using the simple development dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
